spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/musicat?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: a702!
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
server:
  port: 9999