spring:
  datasource:
#    url: jdbc:mariadb://musicat.kr:3306/musicat?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    url: jdbc:mariadb://localhost:3306/musicat?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: ssafy
#    password: ssafya702!
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
server:
  port: 9999

# jwt secret key
jwt:
  secret:
    key: hVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x